# DEPRECATED (2026-04-16): 이 스크립트는 중복 삽입 버그로 대시보드를 망가뜨린 원인입니다. 절대 재실행 금지. 기록 보존용으로만 남겨둠.
import re
FILE = r"frontend/src/pages/DashboardPage.tsx"
with open(FILE, "r", encoding="utf-8") as f:
    src = f.read()
src = src.replace("import { modelsAPI, castingsAPI } from '@/services/api';","import { modelsAPI, castingsAPI, settlementsAPI } from '@/services/api';")
RECHARTS_IMPORT = "import {\n  PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis,\n  CartesianGrid, Tooltip, Legend, ResponsiveContainer\n} from 'recharts';\n"
if "from 'recharts'" not in src:
    src = src.replace("import {\n  LayoutDashboard,", RECHARTS_IMPORT + "import {\n  LayoutDashboard,")
OLD_STATE = "  const [modelCount, setModelCount] = useState<string>('-');\n  const [castingCount, setCastingCount] = useState<string>('-');"
NEW_STATE = "  const [modelCount, setModelCount] = useState<string>('-');\n  const [castingCount, setCastingCount] = useState<string>('-');\n  const [modelChartData, setModelChartData] = useState<{name:string;value:number}[]>([]);\n  const [castingChartData, setCastingChartData] = useState<{name:string;value:number}[]>([]);\n  const [settlementData, setSettlementData] = useState<{income:number;expense:number}>({income:0,expense:0});"
src = src.replace(OLD_STATE, NEW_STATE)
OLD_EFFECT = "  useEffect(() => {\n    modelsAPI.stats()\n      .then((data: any) => setModelCount(data.total?.toLocaleString() || '0'))\n      .catch(() => setModelCount('0'));\n    castingsAPI.stats()\n      .then((data: any) => {\n        const total = Object.values(data.by_status || {}).reduce((a: any, b: any) => a + b, 0);\n        setCastingCount(String(total));\n      })\n      .catch(() => setCastingCount('0'));\n  }, []);"
NEW_EFFECT = "  useEffect(() => {\n    modelsAPI.stats()\n      .then((data: any) => {\n        setModelCount(data.total?.toLocaleString() || '0');\n        const genderMap: Record<string,string> = { male:'남성', female:'여성', other:'기타' };\n        setModelChartData(Object.entries(data.by_gender || {}).map(([k,v]) => ({ name: genderMap[k]||k, value: Number(v) })));\n      })\n      .catch(() => setModelCount('0'));\n    castingsAPI.stats()\n      .then((data: any) => {\n        const statusMap: Record<string,string> = { pending:'검토중', in_progress:'진행중', completed:'완료', cancelled:'취소' };\n        setCastingCount(String(Object.values(data.by_status || {}).reduce((a: any, b: any) => a + b, 0)));\n        setCastingChartData(Object.entries(data.by_status || {}).map(([k,v]) => ({ name: statusMap[k]||k, value: Number(v) })));\n      })\n      .catch(() => setCastingCount('0'));\n    settlementsAPI.stats()\n      .then((data: any) => setSettlementData({ income: data.total_income||0, expense: data.total_expense||0 }))\n      .catch(() => {});\n  }, []);"
src = src.replace(OLD_EFFECT, NEW_EFFECT)
CHART_SECTION = """\n      {/* 통계 차트 */}\n      <div className=\"grid grid-cols-1 lg:grid-cols-3 gap-6\">\n        <div className=\"bg-white rounded-2xl p-6 shadow-sm border border-gray-100\">\n          <h3 className=\"text-lg font-semibold mb-4\">모델 성별 분포</h3>\n          {modelChartData.length > 0 ? (\n            <ResponsiveContainer width=\"100%\" height={200}>\n              <PieChart><Pie data={modelChartData} cx=\"50%\" cy=\"50%\" outerRadius={70} dataKey=\"value\" label={({name,value})=>`${name} ${value}`}>{modelChartData.map((_,i) => (<Cell key={i} fill={['#6366f1','#ec4899','#a3e635'][i%3]} />))}</Pie><Tooltip /></PieChart>\n            </ResponsiveContainer>\n          ) : (<div className=\"h-[200px] flex items-center justify-center text-gray-400 text-sm\">데이터 없음</div>)}\n        </div>\n        <div className=\"bg-white rounded-2xl p-6 shadow-sm border border-gray-100\">\n          <h3 className=\"text-lg font-semibold mb-4\">캐스팅 현황</h3>\n          {castingChartData.length > 0 ? (\n            <ResponsiveContainer width=\"100%\" height={200}>\n              <BarChart data={castingChartData} barSize={28}><CartesianGrid strokeDasharray=\"3 3\" /><XAxis dataKey=\"name\" tick={{fontSize:12}} /><YAxis allowDecimals={false} tick={{fontSize:12}} /><Tooltip /><Bar dataKey=\"value\" name=\"건수\" fill=\"#818cf8\" radius={[4,4,0,0]} /></BarChart>\n            </ResponsiveContainer>\n          ) : (<div className=\"h-[200px] flex items-center justify-center text-gray-400 text-sm\">데이터 없음</div>)}\n        </div>\n        <div className=\"bg-white rounded-2xl p-6 shadow-sm border border-gray-100\">\n          <h3 className=\"text-lg font-semibold mb-4\">정산 요약</h3>\n          <ResponsiveContainer width=\"100%\" height={200}>\n            <BarChart data={[{name:'수입',value:settlementData.income},{name:'지출',value:settlementData.expense}]} barSize={40}><CartesianGrid strokeDasharray=\"3 3\" /><XAxis dataKey=\"name\" tick={{fontSize:13}} /><YAxis tickFormatter={(v)=>`${(v/10000).toFixed(0)}만`} tick={{fontSize:11}} /><Tooltip formatter={(v:any)=>`${Number(v).toLocaleString()}원`} /><Bar dataKey=\"value\" name=\"금액\" radius={[4,4,0,0]}><Cell fill=\"#34d399\" /><Cell fill=\"#f87171\" /></Bar></BarChart>\n          </ResponsiveContainer>\n        </div>\n      </div>"""
if "통계 차트" not in src:
    src = src.replace("      </div>\n    </div>\n  );\n}", "      </div>" + CHART_SECTION + "\n    </div>\n  );\n}")
with open(FILE, "w", encoding="utf-8") as f:
    f.write(src)
print("완료!")
